from datetime import datetime
from config import db, agents_col, logs_col
from pymongo import errors

# Create a new collection for tracking processed files
files_col = db['user_files']

def save_agent_blueprint(blueprint):
    """Saves the JSON configuration generated by Gemini into MongoDB."""
    try:
        blueprint['created_at'] = datetime.now()
        result = agents_col.update_one(
            {"agent_name": blueprint['agent_name']},
            {"$set": blueprint},
            upsert=True
        )
        if result.upserted_id:
            print(f"💾 New Agent '{blueprint['agent_name']}' saved to Database.")
        else:
            print(f"🔄 Existing Agent '{blueprint['agent_name']}' updated in Database.")
        return True
    except errors.PyMongoError as e:
        print(f"❌ Database Error (Save Blueprint): {e}")
        return False

def get_agent_blueprint(agent_name):
    """Retrieves a specific agent's configuration by its name."""
    try:
        agent = agents_col.find_one({"agent_name": agent_name})
        if not agent:
            print(f"⚠️ Agent '{agent_name}' not found in Database.")
            return None
        return agent
    except errors.PyMongoError as e:
        print(f"❌ Database Error (Fetch Blueprint): {e}")
        return None

def log_agent_activity(agent_name, action, status, details=""):
    """Records every 'Thought' or 'Action' for the audit trail."""
    try:
        log_entry = {
            "agent_name": agent_name,
            "timestamp": datetime.now(),
            "action": action, 
            "status": status, 
            "details": details
        }
        logs_col.insert_one(log_entry)
    except errors.PyMongoError as e:
        print(f"❌ Database Error (Logging Activity): {e}")

def get_agent_history(agent_name, limit=10):
    """Retrieves the most recent actions taken by an agent."""
    try:
        logs = logs_col.find({"agent_name": agent_name}).sort("timestamp", -1).limit(limit)
        return list(logs)
    except errors.PyMongoError as e:
        print(f"❌ Database Error (Fetch History): {e}")
        return []

def register_file_processed(agent_name, file_path):
    """Tracks which user files have been read by which agent."""
    try:
        file_record = {
            "agent_name": agent_name,
            "file_path": file_path,
            "processed_at": datetime.now()
        }
        files_col.insert_one(file_record)
    except errors.PyMongoError as e:
        print(f"❌ Database Error (Register File): {e}")

def list_all_agents():
    """Returns a list of all names of agents stored in Compass."""
    try:
        agents = agents_col.find({}, {"agent_name": 1, "_id": 0})
        return [a['agent_name'] for a in agents]
    except errors.PyMongoError as e:
        print(f"❌ Database Error (Listing Agents): {e}")
        return []

def get_user_email(username):
    """Helper to grab a user's registered email."""
    try:
        from config import users_col
        user = users_col.find_one({"username": username}, {"email": 1, "_id": 0})
        return user['email'] if user else None
    except Exception as e:
        print(f"❌ DB Error: {e}")
        return None

def get_agent_by_name(name):
    """Finds a specific agent blueprint in MongoDB by its name."""
    try:
        # FIXED: Variable name updated to 'agents_col'
        agent = agents_col.find_one({"agent_name": name})
        if agent:
            return agent
        else:
            print(f"⚠️ Warning: No agent found with name '{name}'")
            return None
    except Exception as e:
        print(f"❌ Database Error while fetching agent: {e}")
        return None

def delete_agent_blueprint(agent_name):
    """Deletes an agent permanently from MongoDB."""
    try:
        result = agents_col.delete_one({"agent_name": agent_name})
        if result.deleted_count > 0:
            print(f"🗑️ Deleted Agent: {agent_name}")
            return True
        return False
    except errors.PyMongoError as e:
        print(f"❌ Database Error (Delete Agent): {e}")
        return False