import urllib.parse
from datetime import datetime, timedelta
from config import users_col

def schedule_interview(candidate_name, candidate_email, date_str="Next Week", current_username=None):
    """
    Generates a Google Calendar scheduling link for the candidate's interview.
    Requires ZERO API keys (perfect for Hackathons) and works instantly.
    """
    # 1. Identify the Recruiter (Logged in user)
    recruiter_name = current_username if current_username else "The Hiring Team"
    
    # 2. Set default meeting times (e.g., Tomorrow at 10:00 AM)
    # In a production app, the AI would pass a specific ISO-8601 date parsed from the resume.
    tomorrow = datetime.now() + timedelta(days=1)
    start_time = tomorrow.replace(hour=10, minute=0, second=0)
    end_time = start_time + timedelta(minutes=30) # 30 min interview

    # Google Calendar expects dates in this specific format: YYYYMMDDTHHMMSSZ
    fmt_start = start_time.strftime('%Y%m%dT%H%M%SZ')
    fmt_end = end_time.strftime('%Y%m%dT%H%M%SZ')

    # 3. Construct the Calendar Event Details
    event_title = f"Interview: {candidate_name} & {recruiter_name} (InFynd OS)"
    event_details = f"Automated interview scheduling generated by InFynd Agent OS.\n\nCandidate: {candidate_name}\nEmail: {candidate_email}"
    
    # URL Encode the details so they safely fit in a web link
    url_title = urllib.parse.quote(event_title)
    url_details = urllib.parse.quote(event_details)

    # 4. Build the Google Calendar Template Link
    calendar_link = (
        f"https://calendar.google.com/calendar/render?action=TEMPLATE"
        f"&text={url_title}"
        f"&dates={fmt_start}/{fmt_end}"
        f"&details={url_details}"
        f"&add={candidate_email}"
    )

    # Return a clean summary for the executor logs
    return f"Successfully drafted calendar invite for {candidate_name}. [Action Required: Recruiter must click link to confirm: {calendar_link}]"